apiVersion: v1
kind: Pod
metadata:
  name: log-tester
  namespace: monitoring
  labels:
    app: log-tester
spec:
  containers:
    - name: logger
      image: busybox
      args: [/bin/sh, -c, "while true; do echo 'Log desde el pod de prueba'; sleep 1; done"]
  restartPolicy: Always
