apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: aplicacion-pvc
  namespace: aplicacion
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: do-block-storage-retain
