apiVersion: v1
kind: Service
metadata:
  name: aplicacion-service
  namespace: aplicacion
spec:
  selector:
    app: aplicacion
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
      nodePort: 30080
  type: NodePort
