name: Test K8s Connection

on:
  workflow_dispatch:

jobs:
  check-nodes:
    runs-on: ubuntu-latest

    steps:
      - name: Setup kubectl
        uses: azure/setup-kubectl@v3

      - name: Configurar kubeconfig
        run: |
          mkdir -p $HOME/.kube
          echo "${{ secrets.KUBECONFIG }}" > $HOME/.kube/config
          chmod 600 $HOME/.kube/config

      - name: Listar nodos del clúster
        run: kubectl get nodes

      - name: Listar pods (output amplio)
        run: kubectl get pods -A -o wide
