name: Build and Push Docker Image

on:
  workflow_dispatch:

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: Login en Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Construir imagen desde carpeta APLICACION
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/flask-k8s-app:latest ./APLICACION

      - name: Subir imagen a Docker Hub
        run: docker push ${{ secrets.DOCKER_USERNAME }}/flask-k8s-app:latest
