name: Build, Push and Deploy Flask App

on:
  workflow_dispatch:

jobs:
  build-and-push:
    name: Construir y Subir Imagen a Docker Hub
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: Login en Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Construir imagen Docker
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/flask-k8s-app:latest .

      - name: Subir imagen
        run: docker push ${{ secrets.DOCKER_USERNAME }}/flask-k8s-app:latest

  deploy:
    name: Desplegar en Kubernetes
    runs-on: ubuntu-latest
    needs: build-and-push  # Espera a que termine el job anterior

    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: Instalar kubectl
        uses: azure/setup-kubectl@v3

      - name: Configurar kubeconfig
        run: |
          mkdir -p $HOME/.kube
          echo "${{ secrets.KUBECONFIG }}" > $HOME/.kube/config
          chmod 600 $HOME/.kube/config

      - name: Crear namespace si no existe
        run: kubectl get ns aplicacion || kubectl create ns aplicacion

      - name: Desplegar aplicación
        run: kubectl apply -f k8s/deployment.yaml

      - name: Crear servicio
        run: kubectl apply -f k8s/service.yaml

      - name: Ver pods
        run: kubectl get pods -n aplicacion -o wide
